site_name: ZodKmp
site_description: ZodKmp is a Kotlin Multiplatform implementation of the popular Zod TypeScript validation library. It provides a declarative, type-safe way to validate data in your Kotlin Multiplatform projects.

theme:
  name: material
  icon:
    logo: material/library
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: green
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: green
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  features:
   - navigation.tabs  # 👈 enables top tab bar
  hide:
   - navigation

nav:
  - Home: index.md
  - API Reference:
    - Primitives: api/primitives.md
    - Objects: api/objects.md
    - Collections: api/collections.md
    - Unions: api/unions.md
    - Enums: api/enums.md
    - Intersections: api/intersections.md
    - Transformations: api/transformations.md
    - Refinements: api/refinements.md
  - Changelog: changelog.md

repo_url: https://github.com/piashcse/zodkmp
edit_uri: edit/main/docs/

extra_css:
  - css/extra.css
plugins:
  - search
  - meta  # 👈 Required for per-page 'hide' to work

markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.codehilite
  - markdown.extensions.extra
  - markdown.extensions.toc:
      permalink: true