name: Create Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release (e.g., 1.0.0)'
        required: true
        default: '1.0.0'
      release_title:
        description: 'Release title'
        required: true
        default: 'Release'
      release_body:
        description: 'Release description'
        required: false
        default: 'Automated release'

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Update library version in gradle.properties
        run: |
          sed -i.bak "s/library.version=.*/library.version=${{ github.event.inputs.version }}/" gradle.properties
          cat gradle.properties

      - name: Configure Git
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          
      - name: Commit version changes
        run: |
          git add gradle.properties
          git commit -m "Bump version to ${{ github.event.inputs.version }}"
          
      - name: Create tag and push
        run: |
          git tag v${{ github.event.inputs.version }}
          git push origin main --tags
          
      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ github.event.inputs.version }}
          release_name: ${{ github.event.inputs.release_title }} v${{ github.event.inputs.version }}
          body: ${{ github.event.inputs.release_body }}
          draft: false
          prerelease: false